

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Head from "next/head";
import HeaderProvider from "./components/Header/HeaderProvider";
import Header from "./components/Header/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Junior Forum",
  description: "Generated by Dmytro Shapoval",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-400">
        <HeaderProvider>
          <Header />
          <main className="flex justify-center">{children}</main>
        </HeaderProvider>
        
      </body>
    </html>
  );
}
